version: '3.8'

volumes:
  local_postgres_data: {}
  app_data: {}

services:

  postgres:
    image: postgres:14.7
    volumes:
      - ./local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 30s
      retries: 5

  api:
    build: .
    volumes:
      - ./app_data:/app_data/
    command: node server.js
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
